=== gveloso9983/DAW2020/TPC2/projectrecord.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT projectrecord (cabecalho, apresentacao, abstract, entregavel) >
<!ELEMENT cabecalho (nome-chave, titulo, subtitulo?, data-inicio, data-fim, supervisor) >
<!ELEMENT nome-chave (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT subtitulo (#PCDATA) >
<!ELEMENT data-inicio (#PCDATA) >
<!ELEMENT data-fim (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >

<!ELEMENT apresentacao (nome-equipa, nr-aluno, nome, email) >
<!ELEMENT nome-equipa (#PCDATA) >
<!ELEMENT nr-aluno (#PCDATA) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT email (#PCDATA) >


<!ELEMENT abstract (paragrafo) >
<!ELEMENT paragrafo (texto+) >
<!ELEMENT texto (normal|bold|italic)*  >
<!ELEMENT normal (#PCDATA) >
<!ELEMENT bold (#PCDATA) >
<!ELEMENT italic (#PCDATA) >


<!ELEMENT entregavel (link+) >
<!ATTLIST link href CDATA "path">

=== gveloso9983/DAW2020/TPC2/projectrecord2.xml
<?xml version="1.0"?>
<!DOCTYPE projectrecord SYSTEM "projectrecord.dtd">
<projectrecord>
	<cabecalho>
		<titulo>Criação de Project Record</titulo>
		<subtitulo>Project Record 1</subtitulo>
		<data-inicio>21/10/2020</data-inicio>
		<data-fim>28/10/2020</data-fim>
		<supervisor>José Carlos Ramalho</supervisor>
	</cabecalho>
	<apresentacao>
		<nr-aluno>pg42830</nr-aluno>
		<nome>Gonçalo Veloso</nome>
		<email>pg42830@alunos.uminho.pt</email>
	</apresentacao>
	<abstract>
		<paragrafo>
			<texto>
				<normal>A criação do <bold>primeiro project record</bold> foi realizada um pouco através do estudo dos conceitos de DTD e XML, não podendo comprovar, por mim, que tudo aqui realizado está feito da melhor maneira. </normal>
			</texto>
		</paragrafo>
	</abstract>
	<entregavel>
		<link href="https://github.com/gveloso9983/DAW2020">Github</link>
	</entregavel>
</projectrecord>
